# TODO: why this is not taking effect in git commit (maybe it is a good thing)
repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]

      # Make isort compatible with black: https://github.com/PyCQA/isort/issues/1518
      # Otherwise, we will stuck at a situation where isort and black keep changing files back and forth.
      - id: isort
        name: isort
        entry: isort
        language: python
        args: ["--profile", "black"]
        types: [python]
      - id: black
        name: black
        entry: black
        language: python
        types: [python]